daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - gcp-us-central1b.hub.carbonplan.org
        letsencrypt:
          contactEmail: joe@carbonplan.org
      service:
        loadBalancerIP: 35.222.181.206
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
