pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - hub.carbonplan.org
        letsencrypt:
          contactEmail: joe@carbonplan.org
      service:
        loadBalancerIP: 35.222.181.206
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.carbonplan.org/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-gcp-us-central1-b-prod-dask-gateway.prod:80"
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-gcp-us-central1-b-prod-dask-gateway.prod"
      extraEnv:
        OAUTH2_AUTHORIZE_URL: "https://carbonplan.auth0.com/authorize"
        OAUTH2_TOKEN_URL: "https://carbonplan.auth0.com/oauth/token"
        OAUTH_CALLBACK_URL: "https://hub.carbonplan.org/hub/oauth_callback"
