pangeo:
  jupyterhub:
    # proxy:
    #   https:
    #     enabled: true
    #     hosts:
    #       - hub.carbonplan.org
    #     letsencrypt:
    #       contactEmail: jhamman@ucar.edu
    #   service:
    #     loadBalancerIP: 35.238.205.43

    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.carbonplan.org/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "tls://scheduler-public-dev-prod-dask-gateway:8786"
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://web-public-dev-prod-dask-gateway"
