pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.hub.carbonplan.org
        letsencrypt:
          contactEmail: joe@carbonplan.org
      service:
        loadBalancerIP: 35.222.122.192
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://staging.hub.carbonplan.org/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-staging-dask-gateway.staging:80"
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-staging-dask-gateway.staging"
