pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.hub.carbonplan.org
        letsencrypt:
          contactEmail: joe@carbonplan.org
      service:
        loadBalancerIP: 35.222.122.192
      resources:
        requests:
          cpu: "0.01"
          memory: "0.01Gi"
        limits:
          cpu: "1"
          memory: "0.5Gi"
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://staging.hub.carbonplan.org/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-gcp-us-central1-b-staging-dask-gateway.staging:80"
    hub:
      resources:
        requests:
          cpu: "0.01"
          memory: "0.01Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-gcp-us-central1-b-staging-dask-gateway.staging"
      extraEnv:
        OAUTH2_AUTHORIZE_URL: "https://carbonplan.auth0.com/authorize"
        OAUTH2_TOKEN_URL: "https://carbonplan.auth0.com/oauth/token"
        OAUTH_CALLBACK_URL: "https://staging.hub.carbonplan.org/hub/oauth_callback"
