daskhub:
  jupyterhub:
    proxy:
      https:
        enabled: true
        hosts:
          - staging.gcp-us-central1b.hub.carbonplan.org
        letsencrypt:
          contactEmail: joe@carbonplan.org
      service:
        loadBalancerIP: 35.222.122.192
      resources:
        requests:
          cpu: "0.01"
          memory: "0.01Gi"
        limits:
          cpu: "1"
          memory: "0.5Gi"
    hub:
      resources:
        requests:
          cpu: "0.01"
          memory: "0.01Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
