apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: pangeo-deploy
version: 0.1.0
dependencies:
  - name: pangeo
    version: "v0.2.2-n063.h716913e"
    repository: https://pangeo-data.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
