apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: pangeo-deploy
version: 0.2.0
dependencies:
  - name: daskhub
    version: "4.5.7"
    repository: https://helm.dask.org
    import-values:
      - child: rbac
        parent: rbac
