name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2020.08.31
  - adlfs #=0.4
  - altair
  - altair_data_server
  - awscli
  - boto3
  - bokeh
  - bottleneck
  - cartopy
  - cftime
  - cmip6_preprocessing
  - cython=0.28  # for vtzero
  - gdal=2.4.2
  - libgdal=2.4.2
  - earthengine-api
  - fastparquet
  - gcsfs
  - geopandas
  - geoviews
  - h5py
  - h5netcdf
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipytree
  - ipywidgets
  - matplotlib
  - nb_conda_kernels
  - nc-time-axis
  - netcdf4
  - nodejs
  - numcodecs
  - numpy
  - pandas
  - pre_commit
  - mpl-probscale
  - prefect
  - pydap
  - pyproj
  - pyresample
  - pystac
  - pystan
  - pytest
  - python-graphviz
  - python-wget
  - rasterio=1.0.25
  - richdem
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tippecanoe
  - tqdm
  - xarray=0.16.0
  - xlrd
  - xesmf
  - xpublish
  - yarn
  - zarr
  - pip
  - pip:
      - carbonplan[styles,data]
      - numbagg
      - rechunker
      - rio-tiler-mvt
      - showit
      - vtzero
      - cmip6-preprocessing
      - git+https://github.com/jhamman/scikit-downscale.git@master
      - git+https://github.com/dask/adlfs.git@master
      - git+https://github.com/jhamman/zarr.git@fix/absstore
