name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2020.08.31
  - adlfs
  - altair
  - altair_data_server
  - awscli
  - boto3
  - bokeh <2.1
  - bottleneck
  - cartopy
  - cftime
  - cython=0.28  # for vtzero
  - gdal=2.4.2
  - libgdal=2.4.2
  - fastparquet
  - gcsfs
  - geopandas
  - geoviews
  - h5py
  - h5netcdf
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipytree
  - ipywidgets
  - matplotlib
  - nb_conda_kernels
  - nc-time-axis
  - netcdf4
  - nodejs
  - numcodecs
  - numpy
  - pandas
  - mpl-probscale
  - prefect
  - pydap
  - pyproj
  - pyresample
  - pystac
  - pystan
  - pytest
  - python-graphviz
  - python-wget
  - rasterio=1.0.25
  - richdem
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tippecanoe
  - tqdm
  - xarray>=0.16
  - xesmf
  - xpublish
  - yarn
  - zarr
  - pip
  - pip:
      - numbagg
      - rechunker>=0.2
      - rio-tiler-mvt
      - showit
      - vtzero
      - git+git://github.com/carbonplan/carbonplan-python.git
      - git+git://github.com/carbonplan/styles.git
      - git+git://github.com/carbonplan/data.git
      - git+git://github.com/carbonplan/forests.git
