name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2020.10.08  # don't bump until we bump the dask-gateway chart
  - adlfs
  - altair
  - altair_data_server
  - astropy
  - awscli
  - boto3
  - bokeh
  - bottleneck
  - cartopy
  - cftime
  - cmip6_preprocessing
  - code-server >=3.2
  - cython=0.28  # for vtzero
  - gdal=2.4.2
  - libgdal=2.4.2
  - earthengine-api
  - fastparquet
  - fire
  - gcsfs
  - geopandas
  - geoviews
  - h5py
  - h5netcdf
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipython=7.10
  - ipyleaflet
  - ipytree
  - ipywidgets
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - matplotlib
  - metpy
  - metsim
  - nb_conda_kernels
  - nc-time-axis
  - netcdf4
  - nodejs
  - numba
  - numcodecs
  - numpy
  - pandas
  - pre_commit
  - mpl-probscale
  - prefect
  - pydap
  - pykdtree
  - pyproj
  - pyresample
  - pystac
  - pystan
  - pytest
  - python-graphviz
  - python-wget
  - rasterio=1.0.25
  - richdem
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tippecanoe
  - tqdm
  - verde
  - vega_datasets
  - xarray
  - xlrd
  - xesmf
  - xlrd
  - xpublish
  - yarn
  - zarr
  - pip
  - pip:
      - carbonplan
      - carbonplan-data
      - carbonplan-forests
      - carbonplan-styles
      - numbagg
      - rechunker
      - rio-tiler-mvt
      - showit
      - vtzero
      - git+https://github.com/jhamman/scikit-downscale.git@master  # wip
      - git+https://github.com/dask/adlfs.git@master  # for fixes related to async
      - git+https://github.com/jhamman/zarr.git@fix/absstore  # for current version of azure api
      - git+https://github.com/jhamman/climate_indices.git@no-nco  # for no-nco deps
      - git+https://github.com/altair-viz/altair_data_server.git  # for remote hosting
      - git+https://github.com/carbonplan/cmip6-downscaling.git@c5bc63992b38d7c9b6c85b887585cd316019f9c5
