name: carbonplan
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pangeo-notebook=2020.05.10
  - altair
  - altair_data_server
  - astropy
  - bottleneck
  - cartopy
  - cftime
  - h5netcdf
  - intake
  - intake-xarray
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numcodecs
  - numpy
  - pandas
  - pydap
  - pyproj
  - pyresample
  - pystan
  - pytest
  - rasterio
  - richdem
  - rio-cogeo
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - xarray
  - xpublish
  - zarr
  - pip
  - pip:
      - showit
      - numbagg
    #   - git+git://github.com/jhamman/treeplan.git@cloud_reorg
    #   - git+git://github.com/jhamman/carbonplan-styles.git
