name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-dask=2020.10.08  # don't bump until we bump the dask-gateway chart
  - pangeo-notebook=2020.10.08  # don't bump until we bump the dask-gateway chart
  - adlfs
  - altair
  - altair_data_server
  - azure-storage-blob=12.8.1
  # - astropy
  # - awscli
  - boto3
  - bokeh
  - bottleneck
  - cartopy
  - cftime
  # - cmip6_preprocessing
  - code-server >=3.2
  - cython=0.28  # for vtzero
  - fastparquet
  - fuzzywuzzy
  # - fire
  - gcsfs
  - gdal #=2.4.2
  - geopandas
  - geoviews
  - git-crypt
  # - gspread
  - h5py
  - h5netcdf
  - hvplot
  # - hypothesis
  - intake
  - intake-esm
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipython=7.10
  - ipyleaflet
  - ipytree
  - ipywidgets
  - jedi=0.17.2  # https://github.com/ipython/ipython/issues/12740
  - jupyterlab=2.2.9
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - libgdal  #=2.4.2
  - matplotlib
  # - metpy
  # - mpl-probscale
  - nb_conda_kernels
  - nc-time-axis
  - netcdf4
  - nodejs
  - numba
  - numcodecs
  - numpy
  - oauth2client
  - openpyxl
  - pandas
  - pre_commit
  - prefect=0.15.5
  - pydap
  - pykdtree
  - pygeos #>=0.6
  - pygraphviz
  - pyproj
  - pyresample
  - pysal
  - pystac
  - pystan
  - pytest
  - python-graphviz
  - python-wget
  - rasterio  #=1.0.25
  - rechunker
  - regionmask
  # - richdem
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  # - tippecanoe
  - tqdm
  # - verde
  - vega_datasets
  - xarray
  - xesmf
  - xgboost
  - xlrd
  - xpublish
  - yarn
  - zarr
  - pip
  - pip:
      - carbonplan
      - carbonplan-data
      - carbonplan-forests
      - carbonplan-styles
      - numbagg
      - rio-tiler-mvt
      - showit
      - vtzero
      - git+https://github.com/altair-viz/altair_data_server.git  # for remote hosting
      - git+https://github.com/pangeo-forge/pangeo-forge-recipes.git
