#!/bin/bash

source activate notebook

jupyter labextension install --debug -y --minimize False dask-labextension @jupyter-widgets/jupyterlab-manager

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
