#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="carbonplan-gcp-us-cental-1"
export SCRATCH="gs://carbonplan-scratch"
export INTAKE_PATH="https://raw.githubusercontent.com/carbonplan/data/master/intake-catalogs/master.yaml"
export INTAKE_PERSIST_PATH="${SCRATCH}/intake-persist/${JUPYTERHUB_USER}/"

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
