name: Build
on:
  pull_request:
    branches-ignore:
    - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install base apt packages
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git-crypt jq golang-go

    - name: Checkout Repository
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0  # 0 indicates all history.

    - name: setup python
      uses: actions/setup-python@v3.1.1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt

    - name: Determine range of commits we are building
      run: echo "COMMIT_RANGE=${{ github.event.before }}" >> $GITHUB_ENV

    - name: Test building gcp-us-central1-b image if needed
      run: |
        if [ -z "${COMMIT_RANGE}" ]
        then
            hubploy build gcp-us-central1-b
        else
            hubploy build gcp-us-central1-b --commit-range ${COMMIT_RANGE}
        fi

    - name: Test building az-west-us image if needed
      run: |
        if [ -z "${COMMIT_RANGE}" ]
        then
            hubploy build az-west-us
        else
            hubploy build az-west-us --commit-range ${COMMIT_RANGE}
        fi
