name: Build
on:
  push:
    branches-ignore:
      - staging
      - prod
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install base apt packages
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git-crypt jq golang-go

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 0 indicates all history.

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: pre-commit/action@v2.0.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt

    - name: Determine range of commits we are building
      run: echo ::set-env name=COMMIT_RANGE::${{ github.event.before }}""

    - name: Test building gcp-us-central1-b image if needed
      run: hubploy build gcp-us-central1-b --commit-range ${COMMIT_RANGE}
