name: Build
on:
  push:
    branches:
      - master  # TODO: staging/prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install base apt packages
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git-crypt jq golang-go

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine range of commits we are building
      run: echo ::set-env name=COMMIT_RANGE::${{ github.event.before }}""

    - name: Test building gcp-us-central1-b image if needed
      run: hubploy build gcp-us-central1-b --commit-range ${COMMIT_RANGE}
