name: Build
on:
  push:
    branches:
      - master  # TODO: staging/prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install base apt packages
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git-crypt jq golang-go

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
