name: staging to prod
on:
  push:
    branches:
      - staging
jobs:
  stagingToProd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          ref: prod
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
      - name: get commits
        run: |
          echo 'COMMITS<<EOF' >> $GITHUB_ENV
          git log --oneline --no-merges remotes/origin/prod...remotes/origin/staging -- >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV


      - name: pull-request
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: "staging"
          destination_branch: "prod"
          pr_title: prod <- staging
          pr_body: |
            Updates <code>prod</code> from <code>staging</code>.

            <details>
            <summary>Commits</summary>
            ${COMMITS}
            </details>
          github_token: ${{ secrets.GITHUB_TOKEN }}
